baseURL = "/"
themesDir = "themes"
theme = "serif"
languageCode = "de-DE"
title = "Physiotherapie Ricklin-Thiry"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  # In most cases you will only want to set the google_analytics_id OR the google_tag_manager_id. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
  google_analytics_id = ""
  google_tag_manager_id = ""

  [params.homepage]
    show_contact_box = true      # show / hide the contaxt box on the homepage
    show_services_button = false # show / hide the "view all services" button

  [params.logo]
    mobile = "images/logo/logo_ricklin.png"
    mobile_height = "36px"
    desktop = "images/logo/logo_ricklin.png"
    desktop_height = "80px"
    alt = "Serif - A Hugo Business Theme"

  [params.fonts]
    # sets the google font link in layouts/partials/google-fonts.html
    google_fonts = 'https://fonts.googleapis.com/css2?family=Playfair+Display:wght@600&family=Source+Sans+Pro:wght@400;700&display=swap'
    heading = "Playfair Display"
    base = "Source Sans Pro"

  [params.colors]
    primary = "#77ab22"
    black = "#2f2f41"
    white = "#ffffff"
    white_offset = "#f6f7ff"
    grey = "#5C5A5A"

  [params.services]
    summary_truncate = 120 # How many characters to include in the summary of the services before truncating

  [params.team]
    summary_large_truncate = 120 # How many characters to include in the summary of the team bios (large layout) before truncating

  [params.footer]
    copyright_text = '© 2022 Thomas Ricklin-Thiry'

[menu]
  # Main Menu
  [[menu.main]]
    name = "Therapiemöglichkeiten"
    url = "/services/"
    weight = 1

  [[menu.main]]
    name = "Über Mich"
    url = "/ueber-mich/"
    weight = 2

  # [[menu.main]]
  #   name = "Aktuelles"
  #   url = "/aktuelles/"
  #   weight = 3

  [[menu.main]]
    name = "Kontakt"
    url = "/kontakt/"
    weight = 4

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.footer]]
    name = "Kontakt"
    url = "/kontakt/"
    weight = 2

  [[menu.footer]]
    name = "Impressum"
    url = "/impressum/"
    weight = 3

  [[menu.footer]]
    name = "Datenschutz"
    url = "/datenschutz/"
    weight = 4